version: '3'
services:
  app: 
    build: .  
    container_name: api
    network_mode: host
    ports:
      - 5000:5000
    expose:
      - 5000
    volumes:
      - ./src:/var/www
    env_file:
      - ./src/.env
  
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=api_lumen
      - MONGO_INITDB_ROOT_PASSWORD=docker
    ports: 
      - 27017:27017
    expose:
      - 27017

  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 6379:6379
    expose:
      - 6379